config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "dashboards#index"
  resources :sellers
  resources :buyers
  get "/search", to: "buyers#search"

  resources :carts
  resources :orders
  resources :order_details
  resources :wishlists
  resources :hidelists

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    if user.seller?
      cannot :manage, Cart
      cannot :manage, Order
      # cannot :manage, OrderDetail
      can :manage, Product
      cannot :manage, Wishlist
      can :manage, Hidelist
    else
      can :manage, Cart
      can :manage, Order
      # can :manage, OrderDetail
      cannot :manage, Product
      can :manage, Wishlist
      cannot :manage, Hidelist
    end
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
end

app/models/featurelist.rb
class Featurelist < ApplicationRecord
 
end

app/models/hidelist.rb
class Hidelist < Featurelist
    belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
   
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :wishlists, dependent: :destroy
  has_many :hidelists, dependent: :destroy
 
end

app/models/wishlist.rb
class Wishlist < Featurelist
    belongs_to :user
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
    load_and_authorize_resource :class => "Cart"
    def index
        @user = current_user
        @products = Product.all
    end

    def search
        @user = current_user
        @products = Product.where("name Like :search", search: "%#{params[:query]}%")
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    authorize_resource
    def index
        @user = current_user
        @carts =  @user.carts
        
    end

    def create
        @user = current_user
        @cart =  @user.carts.new(product_params)
        if  @cart.save
           
            # @product = Product.find(@cart.product_id)
            # @product.stock = @product.stock - @cart.quantity
        
            # @product.save

            redirect_to buyers_path
      
        end
        
    end

    def update
        @user = current_user
        @cart = Cart.find(params[:id])
        # @cart_old_quantity = @cart.quantity
       
        if @cart.update(cart_params)
            # @product = Product.find(@cart.product_id)
            # if(@cart_old_quantity > @cart.quantity)
            #     @product.stock = @product.stock + (@cart_old_quantity - @cart.quantity)

            # else
            #     @product.stock = @product.stock - (@cart.quantity - @cart_old_quantity)
            # end
            # @product.save

            redirect_to  carts_path
       
        end
    end

    def destroy
        @cart = Cart.find(params[:id])
        # @product = Product.find(@cart.product_id)
        
        # @product.stock = @product.stock + @cart.quantity
        # @product.save
        @cart.destroy
    
        redirect_to buyers_path
      end

    private
        def product_params
            params.require(:product).permit(:product_id, :quantity)
        end
        def cart_params
            params.require(:cart).permit(:product_id, :quantity)
        end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
    skip_before_action :authenticate_user!
    def index
    
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    load_and_authorize_resource
    def index
        @user = current_user
        @orders = @user.orders 
    end

    def show
        @order = Order.find(params[:id])
        if current_user.orders.ids.include? @order.id
            @order_details = @order.order_details
        else
            redirect_to orders_path
        end
    end

    def create
        @user = current_user
        @carts = @user.carts
        # @total = 0
        # @carts.each do |cart|
        #     @product = Product.find(cart.product_id)
        #     @total = @total  + (@product.price * cart.quantity)
        # end
        
        @order =  @user.orders.new(total_params)

        if  @order.save
            @carts.each do |cart|
                @product = Product.find(cart.product_id)
                @product.stock = @product.stock - cart.quantity
                @product.save


                @order_details = @order.order_details.new(product_id: cart.product_id, quantity: cart.quantity, subtotal: (@product.price * cart.quantity))
                @order_details.save
            end
            @user.carts.destroy_all


            
            redirect_to order_path(@order)
        end
      
    end

    private
    def total_params
      params.permit(:total)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/hidelists_helper.rb
module HidelistsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/dashboards/index.html.erb
<br>

<% if user_signed_in? %>
 <div class="container">
 <h2 class="text-center">Dashboard</h2>
    <ul class="list-group">
            <%if current_user.seller == true%>
            
                <li class="list-group-item" style=" background-color: rgba(255,255,255,0.5); " ><%= link_to '1. Show My Products', sellers_path%></li>
                
                <li class="list-group-item" style=" background-color: rgba(255,255,255,0.5); "><%=link_to '2. Add New Products', new_seller_path%></li>
                
                <li class="list-group-item" style=" background-color: rgba(255,255,255,0.5); "><%=link_to '3. Go To Hidelist', hidelists_path%></li>
            

            
            <%else%>
            
                <li class="list-group-item" style=" background-color: rgba(255,255,255,0.5); "><%=link_to '1. Show All Products', buyers_path, data: { turbolinks: false }%></li>
        
                <li class="list-group-item" style=" background-color: rgba(255,255,255,0.5); "><%=link_to '2. View Cart', carts_path%></li>
            
                <li class="list-group-item" style=" background-color: rgba(255,255,255,0.5); "><%=link_to '3. Go To Wishlist', wishlists_path%></li>
            
                <li class="list-group-item" style=" background-color: rgba(255,255,255,0.5); "><%=link_to '4. show My Orders', orders_path%></li>
            
            <%end%>
            <li class="list-group-item"><%=link_to 'Logout', destroy_user_session_path, method: :delete%></li>
        </ul> 
 </div>
<%else%>
<div class="container">
 <h2 class="text-center">Please login to continue</h2>
 <ul class="list-group">
     <li class="list-group-item"><%=link_to 'Login', new_user_session_path%></li>
</ul>
</div>
<%end%>