config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "dashboards#index"
  resources :sellers
  resources :buyers
  get "/search", to: "buyers#search"

  resources :carts
  resources :orders
  resources :order_details
  resources :wishlists
  resources :hidelists

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    if user.seller?
      cannot :manage, Cart
      cannot :manage, Order
      # cannot :manage, OrderDetail
      can :manage, Product
      cannot :manage, Wishlist
      can :manage, Hidelist
    else
      can :manage, Cart
      can :manage, Order
      # can :manage, OrderDetail
      cannot :manage, Product
      can :manage, Wishlist
      cannot :manage, Hidelist
    end
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
end

app/models/featurelist.rb
class Featurelist < ApplicationRecord
 
end

app/models/hidelist.rb
class Hidelist < Featurelist
    belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
   
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :wishlists, dependent: :destroy
  has_many :hidelists, dependent: :destroy
 
end

app/models/wishlist.rb
class Wishlist < Featurelist
    belongs_to :user
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
    load_and_authorize_resource :class => "Cart"
    def index
        @user = current_user
        @products = Product.all
    end

    def search
        @user = current_user
        @products = Product.where("name Like :search", search: "%#{params[:query]}%")
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    authorize_resource
    def index
        @user = current_user
        @carts =  @user.carts
        
    end

    def create
        @user = current_user
        @cart =  @user.carts.new(product_params)
        if  @cart.save
           
            # @product = Product.find(@cart.product_id)
            # @product.stock = @product.stock - @cart.quantity
        
            # @product.save

            redirect_to buyers_path
      
        end
        
    end

    def update
        @user = current_user
        @cart = Cart.find(params[:id])
        # @cart_old_quantity = @cart.quantity
       
        if @cart.update(cart_params)
            # @product = Product.find(@cart.product_id)
            # if(@cart_old_quantity > @cart.quantity)
            #     @product.stock = @product.stock + (@cart_old_quantity - @cart.quantity)

            # else
            #     @product.stock = @product.stock - (@cart.quantity - @cart_old_quantity)
            # end
            # @product.save

            redirect_to  carts_path
       
        end
    end

    def destroy
        @cart = Cart.find(params[:id])
        # @product = Product.find(@cart.product_id)
        
        # @product.stock = @product.stock + @cart.quantity
        # @product.save
        @cart.destroy
    
        redirect_to buyers_path
      end

    private
        def product_params
            params.require(:product).permit(:product_id, :quantity)
        end
        def cart_params
            params.require(:cart).permit(:product_id, :quantity)
        end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    load_and_authorize_resource
    def index
        @user = current_user
        @orders = @user.orders 
    end

    def show
        @order = Order.find(params[:id])
        if current_user.orders.ids.include? @order.id
            @order_details = @order.order_details
        else
            redirect_to orders_path
        end
    end

    def create
        @user = current_user
        @carts = @user.carts
        # @total = 0
        # @carts.each do |cart|
        #     @product = Product.find(cart.product_id)
        #     @total = @total  + (@product.price * cart.quantity)
        # end
        
        @order =  @user.orders.new(total_params)

        if  @order.save
            @carts.each do |cart|
                @product = Product.find(cart.product_id)
                @product.stock = @product.stock - cart.quantity
                @product.save


                @order_details = @order.order_details.new(product_id: cart.product_id, quantity: cart.quantity, subtotal: (@product.price * cart.quantity))
                @order_details.save
            end
            @user.carts.destroy_all


            
            redirect_to order_path(@order)
        end
      
    end

    private
    def total_params
      params.permit(:total)
    end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
   load_and_authorize_resource :class => "Product"
    def index
        @user = current_user

    end

    def new
        @user = current_user
        @product = Product.new
    end


    def show
        @user = current_user
        @product = Product.find(params[:id])
       
        if current_user.products.ids.include? @product.id
          @orders = Order.all
        else
            redirect_to sellers_path
        end

    end
    
    def create
        @user = current_user
        @product =  @user.products.new(product_params)

        if  @product.save
            redirect_to sellers_path
        else
        render :new
        end

    end

    def edit
        @user = current_user
        @product = Product.find(params[:id])
    end


  def update
    @user = current_user
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to sellers_path
    else
      render :edit
    end
  end


  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to sellers_path
  end

    private
    def product_params
      params.require(:product).permit(:name, :price, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/hidelists_helper.rb
module HidelistsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/buyers/index.html.erb
<div class="container">
    <h2 class="text-center">All Products</h2>
 
    <%= button_to 'Go to dashboard', root_path, method: :get, type: "button", class: "btn btn-primary", style: "font-size:15px;"%>
    
    <br><br>
    <table class="table">
    <thead><th>Name</th><th>Price</th><th>Stock</th><th>Quantity</th></thead>
    <tbody>
        <%@products.each do |product|%>
          <%if Hidelist.where(product_id: product.id).empty? %>
                <tr>
                <%= form_with model: product, url: carts_path, method: :POST do |form| %>
                    <%=form.hidden_field  :id, name: 'product[product_id]'%>
                    <td> <%=product.name%></td>
                    <td> Rs <%=product.price%></td>
                    <td> <%=product.stock%></td>
                    <%if @user.carts.where(product_id: product.id).empty? %>
                        <td><%=form.number_field :quantity, value: 0, min: 1, max: product.stock%></td>
                    
                        <td> <%= form.submit "Add to cart" %></td>
                    <%else%>
                    <td><%= @user.carts.where(product_id: product.id)[0].quantity%></td>
                        <td> <%= link_to "Go to cart",  carts_path, data: { turbolinks: false }%></td>

                    <%end%>

                    <%if @user.wishlists.where(product_id: product.id).empty? %>
                        <td> <%= link_to "Add to wishlist",  wishlists_path(product_id: product.id),  method: :post, data: { turbolinks: false }%></td>
                    <%else%>
                        <td> <%= link_to "Go to wishlist",  wishlists_path, data: { turbolinks: false }%></td>
                    <%end%>
                <%end%>
                </tr>
            <%end%>
        <%end%>
    </tbody>
    </table>

</div>

app/views/buyers/search.html.erb
<div class="container">
    <br>
    <h2 class="text-center">Showing results for "<%=params[:query]%>"</h2>
    <br>
    <div class="row">
        <div class="col-sm">
            <%= button_to 'Go to dashboard', root_path, method: :get, type: "button", class: "btn btn-primary", style: "font-size:15px;"%>
        </div>
    
         <div class="col-sm">
            <%= form_with url: "/search", method: :get do |form| %>
                
                <%= form.text_field :query, value: params[:query],placeholder:'Search Product..' %>
                <%= form.submit "Search" %>
            <% end %>
        </div>
    </div>
    <br><br>
    <table class="table">
    <thead><th>Name</th><th>Price</th><th>Stock</th><th>Quantity</th></thead>
    <tbody>
        <%@products.each do |product|%>
          <%if Hidelist.where(product_id: product.id).empty? %>
                <tr>
                <%= form_with model: product, url: carts_path, method: :POST do |form| %>
                    <%=form.hidden_field  :id, name: 'product[product_id]'%>
                    <td> <%=product.name%></td>
                    <td> Rs <%=product.price%></td>
                    <td> <%=product.stock%></td>
                    <%if @user.carts.where(product_id: product.id).empty? %>
                        <td><%=form.number_field :quantity, value: 0, min: 1, max: product.stock%></td>
                    
                        <td> <%= form.submit "Add to cart" %></td>
                    <%else%>
                    <td><%= @user.carts.where(product_id: product.id)[0].quantity%></td>
                        <td> <%= link_to "Go to cart",  carts_path, data: { turbolinks: false }%></td>

                    <%end%>

                    <%if @user.wishlists.where(product_id: product.id).empty? %>
                        <td> <%= link_to "Add to wishlist",  wishlists_path(product_id: product.id),  method: :post, data: { turbolinks: false }%></td>
                    <%else%>
                        <td> <%= link_to "Go to wishlist",  wishlists_path, data: { turbolinks: false }%></td>
                    <%end%>
                <%end%>
                </tr>
            <%end%>
        <%end%>
    </tbody>
    </table>

</div>

app/views/sellers/edit.html.erb
<div class="container">
    <h2 class="text-center">Add Product</h2>
    <%= button_to 'Go to dashboard', root_path, method: :get, type: "button", class: "btn btn-primary", style: "font-size:15px;"%>
    <br>

    
    <%= form_with model: @product, url: seller_path, method: :PATCH do |form| %>
     <div class="form-group">
        <%= form.label :name %><br>
        <%= form.text_field :name %>
      </div>
      <div class="form-group">
        <%= form.label :price %><br>
        <%= form.text_area :price %>
     </div>
      <div class="form-group">
        <%= form.label :stock %><br>
        <%= form.text_area :stock %>
      </div>
     <div class="form-group">
        <%= form.submit %>
     </div>
    <% end %>
</div>

app/views/sellers/index.html.erb
<div class="container">
    <h2 class="text-center">My Products</h2>
    <%= button_to 'Go to dashboard', root_path, method: :get, type: "button", class: "btn btn-primary", style: "font-size:15px;"%>
    <br>

    
    <table class="table">
    <thead><th>Name</th><th>Price</th><th>Stock</th></thead>
    <tbody>
        <%@user.products.each do |product|%>
            <tr>
                <td> <%=product.name%></td>
                <td> Rs  <%=product.price%></td>
                <td> <%=product.stock%></td>
                <td><%= link_to "Edit  ", edit_seller_path(product) %>&nbsp;&nbsp;&nbsp;</td>
                <td><%= link_to "show customers ", seller_path(product) %>&nbsp;&nbsp;&nbsp;</td>
                <%if @user.hidelists.where(product_id: product.id).empty? %>
                    <td><%= link_to "Add to hidelist ", hidelists_path(product_id: product.id), method: :post %>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <%else%>
                    <td><%= link_to "Go to hidelist ", hidelists_path %>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <%end%>
                <td><%= link_to "Delete  ", seller_path(product), method: :delete,  data: { confirm: "Are you sure?" }%></td>
            </tr>
        <%end%>
    </tbody>
    </table>
</div>

app/views/sellers/new.html.erb
<div class="container">
  <h2 class="text-center">Add Product</h2>
  <%= button_to 'Go to dashboard', root_path, method: :get, type: "button", class: "btn btn-primary", style: "font-size:15px;"%>
  <br>
  

  <%= form_with model: @product, url: sellers_path, method: :POST do |form| %>
    <div class="form-group">
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </div>
      <div class="form-group">
      <%= form.label :price %><br>
      <%= form.text_area :price %>
    </div>
    <div class="form-group">
      <%= form.label :stock %><br>
      <%= form.text_area :stock %>
    </div>
    <div class="form-group">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/sellers/show.html.erb
 <div class="container">
    <h2 class="text-center">Products customers</h2>
    <%= button_to 'Go to dashboard', root_path, method: :get, type: "button", class: "btn btn-primary", style: "font-size:15px;"%>
    <br>

    <table class="table">
        <thead><th>Customer name</th><th>Order ID</th><th>Quantity</th><th>Subtotal</th></thead>
        <tbody>

        <%@orders.each do |order|%>
            <%order.order_details.where(product_id: @product.id).each do |order_detail|%>
                <%@customer = order_detail.order.user_id%>
                <tr>
                 <td><%=User.find(@customer).name%></td>
                <td><%=order_detail.order.id%></td>
                
                <td><%=order_detail.quantity%></td>
                <td>Rs <%=order_detail.subtotal%></td>
               
                </tr>
             <%end%>
        <%end%>
        </tbody>
    </table>


</div>